pimcore:
    documents:
        class_definitions:
            data:
                map:
                    printpage: Pimcore\Bundle\Web2PrintBundle\Model\Document\Printpage
                    printcontainer: Pimcore\Bundle\Web2PrintBundle\Model\Document\Printcontainer

        types: ['printpage', 'printcontainer']

        routing:
            direct_route_document_types: ['printpage', 'printcontainer']