services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    Pimcore\Bundle\SimpleBackendSearchBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']