services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\CustomReportsBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreCustomReportsBundle')"

    Pimcore\Bundle\CustomReportsBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']