pimcore:
    newsletter:
        source_adapters:
            reportAdapter: pimcore.document.newsletter.factory.report

pimcore_admin:
    user:
        default_key_bindings:
            reports:
                key: 'M'
                alt: true
                shift: true
            customReports:
                key: 'C'
                alt: true
                shift: true